# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build Framework
      working-directory: ./OwlTree
      run: dotnet restore && dotnet build --no-restore
    - name: Build Generator
      working-directory: ./OwlTree.Generator
      run: dotnet restore && dotnet build --no-restore
    - name: Run Unit Tests
      working-directory: ./Tests/Unit
      run: dotnet test --no-build --verbosity normal
    - name: Run Integration Tests
      working-directory: ./Tests/Integration
      run: dotnet test --no-build --verbosity normal
