# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Move to src
      run: cd OwlTree
    - name: Build Framework
      run: dotnet restore && dotnet build --no-restore
    - name: Move to generator
      run: cd ../OwlTree.Generator
    - name: Build Generator
      run: dotnet restore && dotnet build --no-restore
    - name: Move to Unit Tests
      run: cd ../Tests/Unit
    - name: Run Unit Tests
      run: dotnet test --no-build --verbosity normal
    - name: Move to Integration Tests
      run: cd ../Integration
    - name: Run Integration Tests
      run: dotnet test --no-build --verbosity normal
